#!/usr/bin/env sh

frobby=$abs_builddir/src/frobby

if [ "$1" = "_full" ]; then
  shift;
fi

$frobby test 2> /dev/null > /dev/null
if [ $? = 0 ]; then exit 0; fi
echo "*** Internal test failed, rerunning tests with output ***"
$frobby test
