name: Build
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build-system:
          - make
          - cmake
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up environment
        run: |
          if test ${{ matrix.os }} = macos-latest
          then
               brew install llvm
               echo "$(brew --prefix llvm)/bin"           >> $GITHUB_PATH
               SDKROOT=$(xcrun --show-sdk-path)
               echo CXXFLAGS=-"nostdinc++ -isystem $SDKROOT/usr/include/c++/v1 -isystem $SDKROOT/usr/include -I$(brew --prefix)/include" >> $GITHUB_ENV
               echo LDFLAGS="-L$(brew --prefix)/lib"      >> $GITHUB_ENV
               echo "CXX=clang++"                         >> $GITHUB_ENV
          fi
      - name: Build frobby
        run: |
          if test ${{ matrix.build-system }} = make
          then make -j4
          else mkdir -p build/cmake
               cd build/cmake
               cmake -B. -S../.. -GNinja
               ninja
          fi
      - name: Check frobby
        run: |
          if test ${{ matrix.build-system }} = make
          then make test
          fi
